### ISSUE TITLE
Hardware feed hold outside program execution

### ISSUE THREAD

**Issue by kyle-kingsbury** [FabMo/FabMo-G2-Core#31]
Feed hold can be toggled even when a cnc program is not executing. This is not inherently wrong, but deviates from the FabMo expectations. If the button is pressed outside program execution is should be ignored.

**Comment by kyle-kingsbury** [comment]
In cycle_feedhold.cpp, moved

// Reset the request if it's invalid
	if ((cm1.machine_state != MACHINE_CYCLE) || (cm1.motion_state == MOTION_STOP)) {
		cm->hold_state = FEEDHOLD_OFF;          // cannot honor the feedhold request. reset it
	}
To the top of
 
void cm_request_feedhold(cmFeedholdType type, cmFeedholdExit exit)

and encased the rest of the function in an else statement. So if the state is not a machining cycle, or if motion is already stopped, the button will be ignored.

**Comment by RobMackie** [comment]
Closed with merge of PR #33  Will need to open new issue to deal with feed hold during spindle spin up after feedhold but that will likely be in fabmo
