### ISSUE TITLE
we need to look at the synthetos g2 repo commits

### ISSUE THREAD

**Issue by RobMackie** [FabMo/FabMo-G2-Core#56]
We should look at this:
https://github.com/synthetos/g2/issues/484#issuecomment-1190498039
We probably need to submit some pull requests to synthetos repo so we stay somewhat in sync.

**Comment by kyle-kingsbury** [comment]
The solution mentioned in #484 is already implemented in our codebase. We are also up to date on the edge and edge-preview commits. I will look at changes we have made but will probably hold off on any pull requests until we figure out the current motion control bug.
